[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "literoom"
version = "1.0.0"
requires-python = ">=3.10"
dependencies = [
    "click",
    "fastapi",
    "opencv-python-headless",
    "pillow",
    "pyyaml",
    "timezonefinder",
    "uvicorn",
    "open_clip_torch",
    "insightface",
    "onnxruntime",
    "pi-heif",
]

[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]
include = ["literoom*"]

[project.scripts]
literoom = "literoom.cli:main"
literoom-desktop = "literoom.desktop:main"
